import type { HandPattern } from '../domain/types';

export const HANDS: HandPattern[] = [
  { id:'common', zh:'平糊', name:'Common Hand', pts:'1 faan', ptsSG:'1 tai', desc:'The simplest scoring shape. Every set is a chow and the pair is non-scoring (not your seat wind, round wind, or a dragon).', sets: [['d2','d3','d4'], ['b3','b4','b5'], ['c6','c7','c8'], ['d7','d8','d9']], pair: ['b2','b2'], formula:'4 chows · pair' },
  { id:'allpung', zh:'對對糊', name:'All Pungs', pts:'3 faan', ptsSG:'2 tai', desc:'Every set is a pung (or kong). No chows. The most common "real" scoring hand for beginners — the patterns are simpler to spot.', sets: [['d3','d3','d3'], ['b6','b6','b6'], ['c2','c2','c2'], ['we','we','we']], pair: ['dr','dr'], formula:'4 pungs · pair' },
  { id:'mixed', zh:'混一色', name:'Mixed One Suit', pts:'3 faan', ptsSG:'2 tai', desc:'A single number suit plus any honors. Easier to assemble than Pure One Suit — honors give you flexibility.', sets: [['b1','b2','b3'], ['b4','b5','b6'], ['b7','b7','b7'], ['we','we','we']], pair: ['dr','dr'], formula:'1 suit + honors' },
  { id:'pure', zh:'清一色', name:'Pure One Suit', pts:'7 faan', ptsSG:'4 tai', desc:'One suit only. No honors, no other suits. Hard to build — opponents see it coming — but pays big.', sets: [['c1','c2','c3'], ['c4','c5','c6'], ['c7','c8','c9'], ['c2','c3','c4']], pair: ['c5','c5'], formula:'1 suit, no honors' },
  { id:'small3', zh:'小三元', name:'Small Three Dragons', pts:'3 faan', ptsSG:'2 tai', desc:'Pungs of two dragons plus a pair of the third. The pair has to be the dragons — not just any pair.', sets: [['dr','dr','dr'], ['dg','dg','dg'], ['d2','d3','d4'], ['b6','b6','b6']], pair: ['dw','dw'], formula:'2 dragon pungs · dragon pair' },
  { id:'great3', zh:'大三元', name:'Great Three Dragons', pts:'8 faan', ptsSG:'4 tai', desc:'Pungs of all three dragons. The pair is anything else. A showcase hand — Singapore usually treats it as pay-all from the discarder.', sets: [['dr','dr','dr'], ['dg','dg','dg'], ['dw','dw','dw'], ['d3','d4','d5']], pair: ['b7','b7'], formula:'3 dragon pungs · pair' },
  { id:'honors', zh:'字一色', name:'All Honors', pts:'10 faan', ptsSG:'limit', desc:'Every tile is a wind or a dragon. No numbered suit tiles at all. Rare. Pays a limit hand at most tables.', sets: [['we','we','we'], ['ws','ws','ws'], ['dr','dr','dr'], ['dg','dg','dg']], pair: ['dw','dw'], formula:'honors only' },
  { id:'thirteen', zh:'十三么', name:'Thirteen Orphans', pts:'13 faan', ptsSG:'8 tai', desc:'One of every terminal (1 and 9 of each suit) and every honor, plus any one of them as a pair. The famous exception to "4 sets + pair".', flat: ['d1','d9','b1','b9','c1','c9','we','ws','ww','wn','dr','dg','dw','dw'], formula:'special — see flat layout' },
];
